[package]
name = "console"
version = "0.1.0"
edition.workspace = true

[dependencies]
modules = { path = "../../../libs/modules" }

use-cases = { path = "../../core/use-cases" }
gateways = { path = "../../infrastructures/gateways" }
interface-adapters = { path = "../../infrastructures/interface-adapters" }

[lints]
workspace = true
