[package]
name = "rest-api-configurations"
version = "0.1.0"
edition.workspace = true

[dependencies]
boundaries = { path = "../../core/use-cases/boundaries" }
gateways = { path = "../../core/use-cases/gateways" }
interactors = { path = "../../core/use-cases/interactors" }
models = { path = "../../core/use-cases/models" }

rest-api-adapters = { path = "../../infrastructures/adapters/rest-api-adapters" }
chrono-gateways-impl = { path = "../../infrastructures/gateways-impl/chrono-gateways-impl" }
std-gateways-impl = { path = "../../infrastructures/gateways-impl/std-gateways-impl" }

axum = "0.8"
tokio = { version = "1.44", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
