[package]
name = "rest-api-infrastructures"
version = "0.1.0"
edition.workspace = true

[dependencies]
boundaries = { path = "../../../core/use-cases/boundaries" }
gateways = { path = "../../../core/use-cases/gateways" }
models = { path = "../../../core/use-cases/models" }

axum = "0.8"

[lints]
workspace = true
