[workspace]
members = [
    "dcli/core/domain",
    "dcli/core/use-cases",
    "dcli/infrastructures/gateways",
    "dcli/infrastructures/interface-adapters",
    "dcli/configurations/console",
    "libs/modules",
    "libs/types",
    "libs/ddd", "libs/ddd-derive",
    "libs/smart-pointers",
]
resolver = "2"
