[workspace]
members = [
    "dcli/*/*",
    "libs/*",
    "libs/modules",
]
resolver = "2"

# https://doc.rust-lang.org/rustc/lints/listing/index.html
[workspace.lints.rust]
absolute_paths_not_starting_with_crate = "deny"
ambiguous_negative_literals = "forbid"
# async-idents = "allow"
# closure_returning_async_block = "allow"
# deprecated_safe_2024 = "allow"
# disjoint-capture-migration = "allow"
# edition_2024_expr_fragment_specifier = "allow"
# elided-lifetime-in-path = "allow"
# elided_lifetimes_in_paths = "allow"
# explicit_outlives_requirements = "allow"
# ffi_unwind_calls = "allow"
# fuzzy_provenance_casts = "allow"
# if_let_rescope = "allow"
# impl_trait_overcaptures = "allow"
# keyword-idents = "allow"
# keyword_idents_2018 = "allow"
# keyword_idents_2024 = "allow"
# let_underscore_drop = "allow"
# lossy_provenance_casts = "allow"
# macro_use_extern_crate = "allow"
# meta_variable_misuse = "allow"
# missing_abi = "allow"
# missing_copy_implementations = "allow"
# missing_debug_implementations = "allow"
# missing_docs = "allow"
# missing_unsafe_on_extern = "allow"
# multiple_supertrait_upcastable = "allow"
# must_not_suspend = "allow"
# non_ascii_idents = "allow"
# non_exhaustive_omitted_patterns = "allow"
# or-patterns-back-compat = "allow"
# redundant_imports = "allow"
# redundant_lifetimes = "allow"
# rust_2021_incompatible_closure_captures = "allow"
# rust_2021_incompatible_or_patterns = "allow"
# rust_2021_prefixes_incompatible_syntax = "allow"
# rust_2021_prelude_collisions = "allow"
# rust_2024_guarded_string_incompatible_syntax = "allow"
# rust_2024_incompatible_pat = "allow"
# rust_2024_prelude_collisions = "allow"
# single-use-lifetime = "allow"
# single_use_lifetimes = "allow"
# tail_expr_drop_order = "allow"
# trivial_casts = "allow"
# trivial_numeric_casts = "allow"
# unit_bindings = "allow"
# unnameable_types = "allow"
# unqualified_local_imports = "allow"
# unreachable_pub = "allow"
# unsafe_attr_outside_unsafe = "allow"
# unsafe_code = "allow"
# unsafe_op_in_unsafe_fn = "allow"
# unstable_features = "allow"
# unused_crate_dependencies = "allow"
# unused_extern_crates = "allow"
# unused_import_braces = "allow"
# unused_lifetimes = "allow"
# unused_macro_rules = "allow"
# unused_qualifications = "allow"
# unused_results = "allow"
# variant_size_differences = "allow"

# abi_unsupported_vector_types = "warn"
# ambiguous_glob_imports = "warn"
# ambiguous_glob_reexports = "warn"
# ambiguous_wide_pointer_comparisons = "warn"
# anonymous_parameters = "warn"
# array_into_iter = "warn"
# asm_sub_register = "warn"
# async_fn_in_trait = "warn"
# bad_asm_style = "warn"
# bare-trait-object = "warn"
# bare_trait_objects = "warn"
# boxed_slice_into_iter = "warn"
# break_with_label_and_loop = "warn"
# clashing_extern_declarations = "warn"
# coherence_leak_check = "warn"
# confusable_idents = "warn"
# const_evaluatable_unchecked = "warn"
# const_item_mutation = "warn"
# dangling_pointers_from_temporaries = "warn"
# dead_code = "warn"
# dependency_on_unit_never_type_fallback = "warn"
# deprecated = "warn"
# deprecated_where_clause_location = "warn"
# deref_into_dyn_supertrait = "warn"
# deref_nullptr = "warn"
# drop_bounds = "warn"
# dropping_copy_types = "warn"
# dropping_references = "warn"
# duplicate_macro_attributes = "warn"
# dyn_drop = "warn"
# elided_named_lifetimes = "warn"
# ellipsis_inclusive_range_patterns = "warn"
# exported_private_dependencies = "warn"
# for_loops_over_fallibles = "warn"
# forbidden_lint_groups = "warn"
# forgetting_copy_types = "warn"
# forgetting_references = "warn"
# function_item_references = "warn"
# hidden_glob_reexports = "warn"
# impl_trait_redundant_captures = "warn"
# improper_ctypes = "warn"
# improper_ctypes_definitions = "warn"
# incomplete_features = "warn"
# inline_no_sanitize = "warn"
# internal_features = "warn"
# invalid_from_utf8 = "warn"
# invalid_macro_export_arguments = "warn"
# invalid_nan_comparisons = "warn"
# invalid_value = "warn"
# irrefutable_let_patterns = "warn"
# large_assignments = "warn"
# late_bound_lifetime_arguments = "warn"
# legacy_derive_helpers = "warn"
# map_unit_fn = "warn"
# mixed_script_confusables = "warn"
# named_arguments_used_positionally = "warn"
# never_type_fallback_flowing_into_unsafe = "warn"
# no_mangle_generic_items = "warn"
# non-fmt-panic = "warn"
# non_camel_case_types = "warn"
# non_contiguous_range_endpoints = "warn"
# non_fmt_panics = "warn"
# non_local_definitions = "warn"
# non_shorthand_field_patterns = "warn"
# non_snake_case = "warn"
# non_upper_case_globals = "warn"
# noop_method_call = "warn"
# opaque_hidden_inferred_bound = "warn"
# out_of_scope_macro_calls = "warn"
# overlapping-patterns = "warn"
# overlapping_range_endpoints = "warn"
# path_statements = "warn"
# private_bounds = "warn"
# private_interfaces = "warn"
# private_macro_use = "warn"
# ptr_cast_add_auto_to_object = "warn"
# ptr_to_integer_transmute_in_consts = "warn"
# redundant-semicolon = "warn"
# redundant_semicolons = "warn"
# refining_impl_trait_internal = "warn"
# refining_impl_trait_reachable = "warn"
# renamed_and_removed_lints = "warn"
# repr_transparent_external_private_fields = "warn"
# self_constructor_from_outer_item = "warn"
# semicolon_in_expressions_from_macros = "warn"
# special_module_name = "warn"
# stable_features = "warn"
# static-mut-ref = "warn"
# static_mut_refs = "warn"
# suspicious_double_ref_op = "warn"
# trivial_bounds = "warn"
# type_alias_bounds = "warn"
# tyvar_behind_raw_pointer = "warn"
# uncommon_codepoints = "warn"
# unconditional_recursion = "warn"
# uncovered_param_in_projection = "warn"
# undefined_naked_function_abi = "warn"
# unexpected_cfgs = "warn"
# unfulfilled_lint_expectations = "warn"
# ungated_async_fn_track_caller = "warn"
# uninhabited_static = "warn"
# unknown_lints = "warn"
# unknown_or_malformed_diagnostic_attributes = "warn"
# unnameable_test_items = "warn"
# unreachable_code = "warn"
# unreachable_patterns = "warn"
# unstable-name-collision = "warn"
# unstable_name_collisions = "warn"
# unstable_syntax_pre_expansion = "warn"
# unsupported_fn_ptr_calling_conventions = "warn"
# unused-doc-comment = "warn"
# unused-tuple-struct-fields = "warn"
# unused_allocation = "warn"
# unused_assignments = "warn"
# unused_associated_type_bounds = "warn"
# unused_attributes = "warn"
# unused_braces = "warn"
# unused_comparisons = "warn"
# unused_doc_comments = "warn"
# unused_features = "warn"
# unused_imports = "warn"
# unused_labels = "warn"
# unused_macros = "warn"
# unused_must_use = "warn"
# unused_mut = "warn"
# unused_parens = "warn"
# unused_unsafe = "warn"
# unused_variables = "warn"
# useless_ptr_null_checks = "warn"
# warnings = "warn"
# while_true = "warn"

# ambiguous_associated_items = "deny"
# arithmetic_overflow = "deny"
# binary_asm_labels = "deny"
# bindings_with_variant_name = "deny"
# cenum_impl_drop_cast = "deny"
# conflicting_repr_hints = "deny"
# elided_lifetimes_in_associated_constant = "deny"
# enum_intrinsics_non_enums = "deny"
# exceeding-bitshifts = "deny"
# explicit_builtin_cfgs_in_flags = "deny"
# ill_formed_attribute_input = "deny"
# incomplete_include = "deny"
# ineffective_unstable_trait_impl = "deny"
# invalid_atomic_ordering = "deny"
# invalid_doc_attributes = "deny"
# invalid_from_utf8_unchecked = "deny"
# invalid_reference_casting = "deny"
# invalid_type_param_default = "deny"
# let_underscore_lock = "deny"
# long_running_const_eval = "deny"
# macro_expanded_macro_exports_accessed_by_absolute_paths = "deny"
# missing_fragment_specifier = "deny"
# mutable_transmutes = "deny"
# named_asm_labels = "deny"
# no_mangle_const_items = "deny"
# order_dependent_trait_objects = "deny"
# overflowing_literals = "deny"
# patterns_in_fns_without_body = "deny"
# proc_macro_derive_resolution_fallback = "deny"
# pub_use_of_private_extern_crate = "deny"
# soft_unstable = "deny"
# test_unstable_lint = "deny"
# text_direction_codepoint_in_comment = "deny"
# text_direction_codepoint_in_literal = "deny"
# unconditional_panic = "deny"
# undropped_manually_drops = "deny"
# unknown_crate_types = "deny"
# useless_deprecated = "deny"
# wasm_c_abi = "deny"

# https://rust-lang.github.io/rust-clippy/stable/index.html
[workspace.lints.clippy]
missing_safety_doc = "allow"
needless_return = "allow"
useless_conversion = "allow"
new_without_default = "allow"
missing_transmute_annotations = "allow"

[workspace.metadata.rust-analyzer]
diagnostics.disabled = ["unconventional_variable_names"]
