[workspace]
members = [
    "dcli/*/*",
    "libs/*",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.lints.rust]
# See: https://doc.rust-lang.org/rustc/lints/listing/index.html
non-snake-case = "allow"
non-upper-case-globals = "allow"

[workspace.lints.clippy]
# See: https://rust-lang.github.io/rust-clippy/master/index.html
needless_return = "allow"
needless_return_with_question_mark = "allow"
new_without_default = "allow"
missing_safety_doc = "allow"
useless_conversion = "allow"

[workspace.metadata.rust-analyzer]
diagnostics.disabled = ["unconventional_variable_names"]
