[package]
name = "adapters"
version = "0.1.0"
edition.workspace = true

[dependencies]
axiom = { workspace = true }
serde = { workspace = true }

domain = { path = "../../core/domain" }
boundaries = { path = "../../core/use-cases/boundaries" }
models = { path = "../../core/use-cases/models" }

[lints]
workspace = true
