[package]
name = "console-plain-client-configurations"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true }

models = { path = "../../../core/use-cases/models" }

rest-api-server-adapters = { path = "../../../infrastructures/adapters/servers/rest-api-server-adapters" }

clap = "4.5"
serde_qs = "0.14"
ureq = { version = "3.0", features = ["json"] }

[lints]
workspace = true
