[package]
name = "interactors"
version = "0.1.0"
edition.workspace = true

[dependencies]
axiom = { workspace = true }
serde = { workspace = true }

domain = { path = "../../domain" }
boundaries = { path = "../boundaries" }
gateways = { path = "../gateways" }
models = { path = "../models" }

[lints]
workspace = true
