[package]
name = "gateways"
version = "0.1.0"
edition = "2021"

[dependencies]
modules = { path = "../../../libs/modules" }
ddd = { path = "../../../libs/ddd" }

domain = { path = "../../core/domain" }
use-cases = { path = "../../core/use-cases" }

rayon = "1.10"
triomphe = "0.1.14"
uuid = { version = "1.12", features = [
    "v4", "fast-rng", "macro-diagnostics",
]}
indexmap = "2.7"

[dev-dependencies]
fake = { version = "3.0.1", features = []}
# mockall = "0.13.1"
# proptest = "1.6.0"
