[package]
name = "rest-api-server-adapters"
version = "0.1.0"
edition.workspace = true

[dependencies]
axiom = { workspace = true }
serde = { workspace = true }

boundaries = { path = "../../../../core/use-cases/boundaries" }
gateways = { path = "../../../../core/use-cases/gateways" }
models = { path = "../../../../core/use-cases/models" }

axum = { version = "0.8", features = ["macros"] }

[lints]
workspace = true
