[package]
name = "std-infrastructures"
version = "0.1.0"
edition = "2024"

[dependencies]
axiom = { workspace = true }
serde = { workspace = true }

domain = { path = "../../../core/domain" }
gateways = { path = "../../../core/use-cases/gateways" }
models = { path = "../../../core/use-cases/models" }

[lib]
test = false
doctest = false

[lints]
workspace = true
