[package]
name = "axiom-derive"
version = "0.1.0"
edition.workspace = true

[dependencies]
layout = { package = "axiom-layout", path = "../axiom-layout" }

syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

serde = { version = "1.0", features = ["derive"] }
heck = "0.5.0"

[dev-dependencies]
serde_json = "1.0"

[lib]
proc-macro = true

[lints]
workspace = true
