[package]
name = "use-cases"
version = "0.1.0"
edition.workspace = true

[dependencies]
axiom = { workspace = true }
serde = { workspace = true }

domain = { path = "../domain" }

[features]
boundaries = []
gateways = []
interactors = ["boundaries", "gateways"]

[lib]
test = false
doctest = false

[lints]
workspace = true
