[package]
name = "uuid-gateways-impl"
version = "0.1.0"
edition.workspace = true

[dependencies]
axiom = { workspace = true }

domain = { path = "../../../core/domain" }
gateways = { path = "../../../core/use-cases/gateways" }

uuid = { version = "1.12", features = ["v4", "fast-rng", "macro-diagnostics"] }

[lints]
workspace = true
