name: Lint

on:
  workflow_call:

jobs:
  _:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        channel:
          - nightly

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
          components: rustfmt, clippy

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -Dwarnings

