[package]
name = "litmus"
version = "0.4.0"
description = "a macro-free BDD test harness."
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["bdd", "test", "harness", "cucumber", "gherkin"]
categories = ["development-tools::testing"]
publish = true

[features]
default = []
ahash = ["dep:ahash"]
fxhash = ["dep:fxhash"]
triomphe = ["dep:triomphe"]

[dependencies]
ahash = { version = "0.8", optional = true }
fxhash = { version = "0.2", optional = true }
libtest = { package = "libtest-mimic", version = "0.8" }
strum = { version = "0.27", features = ["derive"] }
triomphe = { version = "0.1", optional = true }

[lib]
test = false
doctest = false

[lints]
workspace = true

[[example]]
name = "main"
path = "examples/main.rs"
harness = false
