[package]
name = "litmus"
version = "0.2.2"
description = "a macro-free BDD test harness."
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["bdd", "test", "harness", "cucumber", "gherkin"]
categories = ["development-tools::testing"]
publish = true

[dependencies]
libtest = { package = "libtest-mimic", version = "0.8" }
strum = { version = "0.27", features = ["derive"] }

[lib]
test = false
doctest = false

[lints]
workspace = true

[[example]]
name = "main"
path = "examples/main.rs"
harness = false
