[package]
name = "litmus"
version = "0.1.0"
description = "a macro-free BDD test harness."
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[dependencies]
libtest = { package = "libtest-mimic", version = "0.8" }
strum = { version = "0.27", features = ["derive"] }

[lib]
test = false
doctest = false

[lints]
workspace = true

[[test]]
name = "main"
path = "tests/main.rs"
harness = false
